name: Setup Playwright with Cache
description: Gets Playwright version, caches binaries, installs dependencies
runs:
  using: "composite"
  steps:
    - name: Get installed Playwright version
      id: playwright-version
      shell: bash
      run: echo "PLAYWRIGHT_VERSION=$(npm list @playwright/test --depth=0 | grep @playwright/test | awk -F@ '{print \$2}')" >> $GITHUB_ENV

    - name: Cache Playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install Node modules
      shell: bash
      run: cd e2e && npm ci

    - name: Install Playwright and dependencies
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: cd e2e && npx playwright install --with-deps