name: Deploy to UAT Environment

on:
  push:
    branches: [uat]
    paths:
      - "force-app/**"

jobs:
  deploy-to-uat:
    uses: ./.github/workflows/action-deploy.yml
    with:
      environment: uat
      case-comment-creation: false
      user-map-for-deployments: false
    secrets: inherit
    permissions:
      actions: write
      security-events: write
      contents: write
      issues: write
      pull-requests: write
